test:
  _target_: src.datasets.CustomDirTextDataset
  instance_transforms: ${transforms.instance_transforms.inference}
  data_dir: "/Users/andreypetukhov/Documents/Машинное-обучение/Neural-Vocoder/texts"
