test:
  _target_: src.datasets.BaseDataset
  instance_transforms: ${transforms.instance_transforms.inference}
  inference: true
  index:
    - text: "Printing, in the only sense with which we are at present concerned, differs from most if not from all the arts and crafts represented in the Exhibition."
      path: "sample.txt"
      audio_len: 0
    - text: "Deep Learning in Audio course at HSE University offers an exciting and challenging exploration of cutting-edge techniques in audio processing, from speech recognition to music analysis. With complex homeworks that push students to apply theory to real-world problems, it provides a hands-on, rigorous learning experience that is both demanding and rewarding."
      path: "sample_1.txt"
      audio_len: 0
    - text: "Dmitri Shostakovich was a Soviet-era Russian composer and pianist who became internationally known after the premiere of his First Symphony in 1926 and thereafter was regarded as a major composer."
      path: "sample_2.txt"
      audio_len: 0
    - text: "Lev Termen, better known as Leon Theremin was a Russian inventor, most famous for his invention of the theremin, one of the first electronic musical instruments and the first to be mass-produced."
      path: "sample_3.txt"
      audio_len: 0
    - text: "Leonard Bernstein was an American conductor, composer, pianist, music educator, author, and humanitarian. Considered to be one of the most important conductors of his time, he was the first American-born conductor to receive international acclaim."
      path: "sample_4.txt"
      audio_len: 0
    - text: "Mihajlo Pupin was a founding member of National Advisory Committee for Aeronautics (NACA) on 3 March 1915, which later became NASA, and he participated in the founding of American Mathematical Society and American Physical Society."
      path: "sample_5.txt"
      audio_len: 0