defaults:
  - generator: default
  - datasets: infer_input2speech
  - dataloader: infer_input2speech
  - transforms: text2spec
  - _self_

inferencer:
  device_tensors: ["spectrogram"]
  device: auto
  save_path: "input2speech_result"
  seed: 1
  from_pretrained: "/Users/andreypetukhov/Documents/Машинное-обучение/Neural-Vocoder/checkpoint-epoch20.pth"