defaults:
  - generator: default
  - datasets: infer_speech2speech # we do not want to run inference on training data
  - dataloader: infer_speech2speech
  - transforms: melspec
  - _self_

inferencer:
  device_tensors: ["spectrogram", "audio"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "speech2speech_result" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "/Users/andreypetukhov/Documents/Машинное-обучение/Neural-Vocoder/checkpoint-epoch20.pth"