defaults:
  - generator: default
  - discriminator: default
  - writer: wandb
  - datasets: ljspeech_kaggle_ob
  - dataloader: ob
  - transforms: melspec
  - _self_

mel_spectrogram:
  _target_: src.transforms.MelSpectrogram
  config: ${transforms.instance_transforms.train.get_spectrogram.config}
  normalize: True

optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 1e-2

gen_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

disc_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

gen_loss_function:
  _target_: src.loss.GeneratorLoss
  config: ${transforms.instance_transforms.train.get_spectrogram.config}

disc_loss_function:
  _target_: src.loss.DiscriminatorLoss

trainer:
  log_step: 10
  n_epochs: 500
  epoch_len: 10
  device_tensors: ["spectrogram", "audio"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min test_loss" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 20 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
  max_grad_norm: 10
