train:
  get_spectrogram:
    _target_: src.transforms.MelSpectrogram
    config:
      sample_rate: 22050
      win_length: 1024
      hop_length: 256
      n_fft: 1024
      f_min: 0
      f_max: 8000
      n_mels: 80
      power: 1.0
      center: false
    normalize: True

inference:
  get_spectrogram:
    _target_: src.transforms.MelSpectrogram
    config:
      sample_rate: 22050
      win_length: 1024
      hop_length: 256
      n_fft: 1024
      f_min: 0
      f_max: 8000
      n_mels: 80
      power: 1.0
      center: false
    normalize: True
